const SEVENREALMS_PRIMARY = "#FFD800";
const SEVENREALMS_PRIMARY_VARIANT = "#FF9400";
const SEVENREALMS_SECONDARY = "#F75C36";
const SEVENREALMS_SECONDARY_VARIANT = "#FFF283";

export {
  SEVENREALMS_PRIMARY,
  SEVENREALMS_PRIMARY_VARIANT,
  SEVENREALMS_SECONDARY,
  SEVENREALMS_SECONDARY_VARIANT,
};
