const SEVENFIELD_PRIMARY = '#FFD800'
const SEVENFIELD_PRIMARY_VARIANT = '#FF9400'
const SEVENFIELD_SECONDARY = '#F75C36'
const SEVENFIELD_SECONDARY_VARIANT = '#FFF283'

export {
  SEVENFIELD_PRIMARY,
  SEVENFIELD_PRIMARY_VARIANT,
  SEVENFIELD_SECONDARY,
  SEVENFIELD_SECONDARY_VARIANT
}
