import Provider from './provider'
import { Head } from '@/components/head'
import { Noto_Sans_SC } from 'next/font/google'
import { HeadBar } from '@/components/headbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// const notoSans = Noto_Sans_SC({
//   weight: ["400", "700", "100", "300", "900", "500"],
//   subsets: ["latin"]
// })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        // className={notoSans.className}
        style={{
          margin: '0'
        }}>
        <Provider>
          <Head />
          <HeadBar />
          {children}
        </Provider>
      </body>
    </html>
  )
}
