import Provider from './provider'
import { Noto_Sans_SC } from 'next/font/google'
import { Header } from '@/components/header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const notoSans = Noto_Sans_SC({
  weight: ["400", "700", "100", "300", "900", "500"],
  subsets: ["latin"]
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={notoSans.className}>
        <Provider>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  )
}
